Repository mangdangroboticsclub/mini_pupper_ros, pull requests merged in 2023-02, with the labels that each got.

#46 Add lint configs and industrial_ci configs
  .flake8
  .github/workflows/industrial_ci.yml
  mini_pupper_bringup/CMakeLists.txt
  mini_pupper_bringup/launch/bringup.launch.py
  mini_pupper_bringup/package.xml
  mini_pupper_description/CMakeLists.txt
  mini_pupper_description/launch/description.launch.py
  mini_pupper_description/package.xml
  mini_pupper_gazebo/CMakeLists.txt
  mini_pupper_gazebo/launch/gazebo.launch.py
  mini_pupper_gazebo/package.xml
  mini_pupper_navigation/CMakeLists.txt
  mini_pupper_navigation/launch/navigate.launch.py
  mini_pupper_navigation/launch/occupancy_grid.launch.py
  mini_pupper_navigation/launch/slam.launch.py
  mini_pupper_navigation/package.xml
Labels: ci

#38 Support Cartographer and Navigation2 in Humble
  mini_pupper_gazebo/launch/gazebo.launch.py
  mini_pupper_navigation/config/move_base/base_local_planner_holonomic_params.yaml
  mini_pupper_navigation/config/move_base/costmap_common_params.yaml
  mini_pupper_navigation/config/move_base/global_costmap_params.yaml
  mini_pupper_navigation/config/move_base/local_costmap_params.yaml
  mini_pupper_navigation/config/move_base/move_base_params.yaml
  mini_pupper_navigation/config/nav2/mini_pupper.yaml
  mini_pupper_navigation/launch/bringup.launch.py
  mini_pupper_navigation/launch/localization.launch.py
  mini_pupper_navigation/launch/navigation.launch.py
  mini_pupper_navigation/launch/occupancy_grid.launch.py
  mini_pupper_navigation/launch/slam.launch.py
  mini_pupper_navigation/package.xml
  mini_pupper_navigation/rviz/cartographer.rviz
  mini_pupper_navigation/rviz/navigation.rviz
Labels: enhancement

#49 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation
